# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 20:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('genre', models.CharField(choices=[('MASCULINO', 'masculino'), ('FEMENINO', 'femenino')], default='-----', max_length=20)),
                ('role', models.CharField(choices=[('ASISTENTE', 'asistente'), ('PONENTE', 'ponente'), ('AMBOS', 'ambos')], default='ASISTENTE', max_length=10)),
                ('age', models.PositiveIntegerField()),
                ('autonomous_community', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
            ],
        ),
    ]
