# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='---@---', max_length=75),
        ),
        migrations.AddField(
            model_name='usuario',
            name='username',
            field=models.CharField(default='---', max_length=50),
        ),
    ]
