# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-12 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_remove_usuario_edad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
    ]
