# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-12 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_auto_20171211_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='autonomous_community',
            field=models.CharField(choices=[('ANDALUCIA', 'ANDALUCIA'), ('ARAGON', 'aragon'), ('ASTURIAS', 'asturias'), ('CANTABRIA', 'cantabria'), ('CASTILLA LA MANCHA', 'castilla la mancha'), ('CASTILLA LEON', 'castilla leon'), ('EXTREMADURA', 'extremadura'), ('GALICIA', 'galicia'), ('LA RIOJA', 'la rioja'), ('MADRID', 'madrid'), ('MURCIA', 'murcia'), ('NAVARRA', 'navarra'), ('PAIS VASCO', 'pais vasco'), ('VALENCIA', 'valencia'), ('BALEARES', 'baleares'), ('CANARIAS', 'canarias'), ('CEUTA', 'ceuta'), ('MELILLA', 'melilla')], default='-----', max_length=50),
        ),
    ]
