# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_auto_20171211_1900'),
        ('principal', '0006_auto_20171213_1907'),
    ]

    operations = [
    ]
