version: '2'
services:
  db:
   image: mysql
   environment:
     MYSQL_ROOT_PASSWORD: egc
     MYSQL_DATABASE: autenticaciondb
     MYSQL_USER: egc
     MYSQL_PASSWORD: egc

  djangorest:
    build: .
    command: python manage.py runserver 127.0.0.1:50020
    volumes:
      - .:/code
    ports:
      - "50020:50020"
    depends_on:
      - db

